services:
  auth:
    build:
      context: ../../unison-auth

  orchestrator:
    build:
      context: ../../unison-orchestrator

  experience-renderer:
    build:
      context: ../../unison-experience-renderer
