services:
  auth:
    build:
      context: ../../unison-auth

  orchestrator:
    build:
      context: ../../unison-orchestrator

  experience-renderer:
    build:
      context: ../../unison-experience-renderer

  agent-vdi:
    build:
      context: ../../unison-agent-vdi

  updates:
    build:
      context: ../../unison-updates
