#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path
from typing import Any


REPO_ROOT = Path(__file__).resolve().parents[1]


def _load_json(path: Path, *, container_service: str) -> dict[str, Any]:
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    raw = subprocess.check_output(
        [
            "docker",
            "compose",
            "--env-file",
            str(REPO_ROOT / ".env"),
            "-f",
            str(REPO_ROOT / "compose/compose.yaml"),
            "-f",
            str(REPO_ROOT / "compose/compose.local-source.yaml"),
            "exec",
            "-T",
            container_service,
            "python3",
            "-c",
            f"from pathlib import Path; print(Path({str(path)!r}).read_text(encoding='utf-8'))",
        ],
        text=True,
    )
    return json.loads(raw)


def _yaml_quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _render_override(artifact: dict[str, Any]) -> str:
    services = artifact.get("services") if isinstance(artifact.get("services"), dict) else {}
    lines = [
        "# Generated by install-staged-update.py",
        f"# source artifact: {artifact.get('plan_id', 'unknown')}",
        "services:",
    ]
    for service in sorted(services):
        meta = services[service] if isinstance(services.get(service), dict) else {}
        image = str(meta.get("image") or "")
        action = str(meta.get("action") or "")
        if not image or action == "remove-image":
            continue
        lines.append(f"  {service}:")
        lines.append(f"    image: {_yaml_quote(image)}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--artifact", required=True, help="Updates apply/rollback artifact path")
    parser.add_argument("--prefix", default="/opt/unison-platform", help="Install prefix for the staged override")
    parser.add_argument("--container-service", default="updates", help="Compose service to query when artifact path is container-local")
    ns = parser.parse_args()

    artifact_path = Path(ns.artifact)
    artifact = _load_json(artifact_path, container_service=ns.container_service)
    if artifact.get("schema_version") != "unison.updates.compose.override.v1":
        raise SystemExit("unexpected artifact schema")

    prefix = Path(ns.prefix)
    staged_dir = prefix / "staged"
    staged_dir.mkdir(parents=True, exist_ok=True)
    override_path = staged_dir / "compose.next-boot.override.yaml"
    metadata_path = staged_dir / "compose.next-boot.metadata.json"

    override_path.write_text(_render_override(artifact), encoding="utf-8")
    metadata = {
        "installed_from": str(artifact_path),
        "installed_at": artifact.get("generated_at"),
        "artifact_kind": artifact.get("artifact_kind"),
        "job_id": artifact.get("job_id"),
        "plan_id": artifact.get("plan_id"),
        "override_path": str(override_path),
    }
    metadata_path.write_text(json.dumps(metadata, indent=2, sort_keys=True) + "\n", encoding="utf-8")

    print(
        json.dumps(
            {
                "ok": True,
                "override_path": str(override_path),
                "metadata_path": str(metadata_path),
                "service_count": len(artifact.get("services") or {}),
            },
            indent=2,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
